# name: Deploy Catalytica Infrastructure (Disabled)

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   deploy:
#     name: Terraform Setup Only
#     runs-on: ubuntu-latest

#     env:
#       TF_VAR_region: us-west-2

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.6.0

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-west-2

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Format Check
#         run: terraform fmt -check

#       - name: Terraform Validate
#         run: terraform validate

#       - name: Terraform Plan
#         run: terraform plan

#       - name: Terraform Apply (Auto-Approve)
#         run: terraform apply -auto-approve

